management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 9099
spring:
  application:
    name: bill-service
  datasource:
    password: test
    url: jdbc:postgresql://localhost:5432/demo
    username: test
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
statistic-service:
  url: http://localhost:9099
tracing:
  url: http://localhost:4318/v1/traces
