otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  resource:
    attributes:
      service: client
      service.name: client
server:
  port: 9096
#  address: my-custom-ip2
spring:
  application:
    name: bill-client
  datasource:
    password: test
    url: jdbc:postgresql://localhost:5432/client
    username: test
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
  security:
    oauth2:
      client:
        registration:
          tech-client:
            authorization-grant-type: client_credentials
            client-id: tech-client
            client-secret: tech-secret
          oidc-client:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://client.127.0.0.1.nip.io:9096/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          tech-client:
            token-uri: http://localhost:7777/auth-server/oauth2/token
          spring:
            issuer-uri: http://auth-server:9000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

service:
  host: http://localhost:9099
allowed:
  domains: test1,test2,test3,test4
statistic-service:
  url: http://localhost:7777/resource-server